DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS contact;

CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	secret VARCHAR(250) NOT NULL
);

CREATE TABLE contact (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	ph VARCHAR(250) NOT NULL,
	email VARCHAR(250) NOT NULL,
	useremail VARCHAR(250) NOT NULL
);